services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
  db_app:
    image: postgres:16
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
  backend_app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: backend_app
    command: ["/app/docker/app.sh"]
    ports:
      - 8000:8000
    volumes:
      - ./doc:/app/doc  # сохраняем файлы на хосте
    depends_on:
      rabbitmq:
        condition: service_healthy
      db_app:
        condition: service_started
    restart: unless-stopped